-- AgroTech Supabase schema
create extension if not exists pgcrypto;

create table if not exists public.users (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  email text not null unique,
  phone text not null,
  password_hash text not null,
  location text default '',
  role text not null default 'farmer' check (role in ('farmer','seller','admin')),
  status text not null default 'active' check (status in ('active','blocked','pending')),
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  price numeric(12,2) not null,
  unit text not null,
  description text default '',
  image text default '',
  rating numeric(3,2) default 0,
  reviews integer default 0,
  available boolean default true,
  location text default '',
  owner_id uuid references public.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.services (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  price numeric(12,2) not null,
  unit text not null,
  description text default '',
  location text default '',
  image text default '',
  rating numeric(3,2) default 0,
  reviews integer default 0,
  available boolean default true,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  posted_by uuid references public.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_id text not null unique,
  user_id uuid references public.users(id) on delete set null,
  product_id bigint references public.products(id) on delete set null,
  product_name text not null,
  quantity integer not null default 1,
  price numeric(12,2) not null,
  payment_method text not null,
  payment_status text not null default 'pending',
  status text not null default 'pending',
  address text default '',
  notes text default '',
  created_at timestamptz not null default now()
);

create table if not exists public.complaints (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users(id) on delete set null,
  subject text not null,
  description text not null,
  priority text not null default 'medium',
  status text not null default 'open',
  created_at timestamptz not null default now()
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  audience text not null default 'all',
  message text not null,
  created_by uuid references public.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists idx_orders_user_id on public.orders(user_id);
create index if not exists idx_services_posted_by on public.services(posted_by);
create index if not exists idx_products_category on public.products(category);

-- Backend uses the Supabase service-role key, so application authorization is handled by FastAPI.
-- RLS is enabled as an additional safety layer; do not expose the service-role key to the browser.
alter table public.users enable row level security;
alter table public.products enable row level security;
alter table public.services enable row level security;
alter table public.orders enable row level security;
alter table public.complaints enable row level security;
alter table public.notifications enable row level security;
